In [1]:
import numpy as np
import random
import scipy
import math

In [2]:
#  1   
a = np.random.random((10,3))
i=0

print("Array:")
print(a)
print("")
print("Numbers:")

for i in range(10):
    if (abs(a[i,0]-0.5) >= abs(a[i,1]-0.5)):
        if abs(a[i,2] - 0.5) >= abs(a[i,1] - 0.5):
            print(a[i,1])
        else:
            print(a[i,2])
    else:
        if abs(a[i,2]-0.5) >= abs(a[i,0]-0.5):
            print(a[i,0])
        else:
            print(a[i,2])

Array:
[[0.19659127 0.35349357 0.80040579]
 [0.2442333  0.44769336 0.19532014]
 [0.19622965 0.46900502 0.27648322]
 [0.25907335 0.8447512  0.44932897]
 [0.43268259 0.22244177 0.95670575]
 [0.30562516 0.7219428  0.04208952]
 [0.51261815 0.11870942 0.12916441]
 [0.91492767 0.0893937  0.91926901]
 [0.49524826 0.96778556 0.62555743]
 [0.13160812 0.74407143 0.3763088 ]]

Numbers:
0.35349356698551426
0.4476933606042136
0.4690050230508971
0.44932896970237635
0.43268259107785
0.30562515958617253
0.5126181535143167
0.08939369882793002
0.49524825508327275
0.37630880309502246


In [3]:
#   2

a = np.random.random((6,6))
print("Matrix: ")
print(a)
print("")

j=0
b=[]

for j in range(6):
    minim = a[0,j]
    for i in range(6):
        if (a[i,j] < minim):
            minim = a[i,j]
    b.append(minim)
    
print("minimum line =  " + str(b))
print("")

i=0
j=0
s=0
c=[]
for i in range(6):
    for j in range(6):
        s += a[i,j]
    c.append(s)
    s=0

print("amount line =  " + str(c))
print("")
i=0
j=0

for i in range(6):
    for j in range(6):
        a[i,j] = c[i] / b[j]
        
print("Now the matrix A is:  ")
print(a)

Matrix: 
[[0.67631902 0.13774792 0.89182685 0.65589173 0.513343   0.62208877]
 [0.98403883 0.80348523 0.34111168 0.14172235 0.20064142 0.32619749]
 [0.35384643 0.38377335 0.81025117 0.73600316 0.43822247 0.75308871]
 [0.43633832 0.55534882 0.37134716 0.55483572 0.29378856 0.57726456]
 [0.40041518 0.29031505 0.61311009 0.45430846 0.19023614 0.13083205]
 [0.95044732 0.94775092 0.23218322 0.77911844 0.94560739 0.34240146]]

minimum line =  [0.353846429431398, 0.13774792139089487, 0.23218321738686043, 0.14172234613796697, 0.19023613834610276, 0.13083205255853914]

amount line =  [3.497217282819421, 2.7971969980645923, 3.4751852828016254, 2.788923150691849, 2.0792169713559012, 4.197508742565226]

Now the matrix A is:  
[[ 9.88343245 25.38853035 15.06231726 24.67654098 18.38355905 26.73058486]
 [ 7.90511579 20.30663672 12.04736944 19.73716266 14.70381507 21.38005896]
 [ 9.82116815 25.22858601 14.96742668 24.52108208 18.26774509 26.56218576]
 [ 7.8817332  20.24657158 12.01173445 19.67878198 1

In [4]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mi=0
for i in range (1,7):
    if x[i-1]==0:
        if x[i] > mi :
            mi = x[i]
print(mi)

5


In [5]:
x=np.ones(10)
a=np.array([0, 1, 2, 3, 5, 5, 5, 8])


print("Before: ")
print(x)

for i in range(9):
    for j in range(8):
        if a[j] == i :
            x[i] += 1
            
print("After: ")
print(x)

Before: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After: 
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [6]:
a = np.arange(16).reshape(4, 4)
N=4
print("Matrix: ")
print(a)
print("")


l=[]
slov={}
i=0; j=0; k=0; p=0

for k in range(2*N-1):     #keys
    
    for i in range (N):
        for j in range (N):
            if i+j == p :
                l.append(a[i,j])
    p += 1
    slov[k] = l
    l = []

print("dict = ")
print(slov)

Matrix: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

dict = 
{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}
